export class RestaurantList {
    relNum: number;
    relName: string;
    relCategory: string;
    relMonStart: string;
    relMonEnd: string;
    relTueStart: string;
    relTueEnd: string;
    relWedStart: string;
    relWedEnd: string;
    relThuStart: string;
    relThuEnd: string;
    relFriStart: string;
    relFriEnd: string;
    relSatStart: string;
    relSatEnd: string;
    relSunStart: string;
    relSunEnd: string;
    relLatitude: number;
    relLongitude: number;
    zoneNum: number;
    subwayNum: number;
    relSubAddress: string;
    relCall: string;
    relCredat: string;
    relCretim: string;
    relModdat: string;
    relModtim: string;
}
